<?php
global $_lang;

$_lang['ja'] = [
    'year' => '年',
    'month' => 'ヶ月',
    'week' => '週',
    'day' => '日',
    'hour' => '時',
    'minu' => '分',
    'sec' => '秒',
    'ago' => '前',
    'justnow' => '直前',
    'title' => 'ボ対検索ツール',
    'search' => '検索',
    'and_search' => 'AND検索',
    'or_search' => 'OR検索',
    'title_checkbox' => 'タイトル',
    'overview_checkbox' => '概要欄',
    'author_checkbox' => '投稿者',
    'tag_checkbox' => 'タグ',
    'unlisted_checkbox' => '限定公開',
    'deleted_checkbox' => '削除済み',
    'all_radio' => 'すべて',
    'vps_radio' => 'ボイパ対決',
    'material_radio' => '素材',
    'use_ai_class' => 'AIによる分類',
    'next' => '次へ',
    'prev' => '前へ',
    'sended_pl' => 'プレイリストを送信しました。',
    'added_pl' => 'プレイリストを追加しました。',
    'sended_vd' => '動画を送信しました。',
    'added_vd' => '動画を追加しました。',
    'reported_video' => '動画を報告しました。',
    'send_pl' => 'データ送信',
    'info' => '情報',
    'compare' => '動画比較',
    'view' => '回視聴',
    'report' => '報告',
    'download' => 'ダウンロード',
    'copy' => 'コピー',

    'sort' => '並び替え',
    'sort_recent' => '投稿日時が新しい順',
    'sort_ancient' => '投稿日時が古い順',
    'sort_most_view' => '再生数が多い順',
    'sort_worst_view' => '再生数が少ない順',
    'sort_most_like' => '高評価が多い順',
    'sort_word' => 'タイトル昇順',
    'sort_word_desc' => 'タイトル降順',
    'sort_random' => 'ランダム順',

    'total' => '総計',
    'next_birth' => 'HIKAKINボイパ対決シリーズ%d周年まで%d日',

    'listview' => 'リスト表示モード',
    'matrixview' => 'マトリックス表示モード',

    'lightmode' => 'ライトモード',
    'darkmode' => 'ダークモード',

    // 認証関連
    'login' => 'ログイン',
    'logout' => 'ログアウト',
    'register' => '新規登録',
    'username' => 'ユーザー名',
    'password' => 'パスワード',
    'email' => 'メールアドレス',
    'login_required' => 'ログインが必要です',

    // お気に入り関連
    'favorites' => 'お気に入り',
    'add_to_favorites' => 'お気に入りに追加',
    'remove_from_favorites' => 'お気に入りから削除',
    'added_to_favorites' => 'お気に入りに追加しました',
    'removed_from_favorites' => 'お気に入りから削除しました',
    'error_occurred' => 'エラーが発生しました',
    
    // 認証エラーメッセージ
    'username_already_exists' => 'ユーザー名が既に使用されています',
    'email_already_exists' => 'メールアドレスが既に使用されています',
    'account_created' => 'アカウントが作成されました',
    'login_success' => 'ログインしました',
    'invalid_credentials' => 'ユーザー名またはパスワードが間違っています',
    'logout_success' => 'ログアウトしました',
    'username_password_required' => 'ユーザー名とパスワードを入力してください',
    
    // 登録フォーム関連
    'register_title' => '新規登録',
    'register_button' => '登録',
    'confirm_password' => 'パスワード確認',
    'redirect_to_login' => 'ログインページに移動してください。',
    'valid_email_required' => '有効なメールアドレスを入力してください',
    'password_min_length' => 'パスワードは6文字以上で入力してください',
    'password_mismatch' => 'パスワードが一致しません',
    'all_fields_required' => 'すべての項目を入力してください',
    'already_have_account' => '既にアカウントをお持ちの方は',
    
    // アカウント設定関連
    'account_settings' => 'アカウント設定',
    'change_username' => 'ユーザー名変更',
    'change_password' => 'パスワード変更',
    'change_email' => 'メールアドレス変更',
    'delete_account' => 'アカウント削除',
    'new_username' => '新しいユーザー名',
    'current_password' => '現在のパスワード',
    'new_password' => '新しいパスワード',
    'new_email' => '新しいメールアドレス',
    'confirm_delete' => '本当にアカウントを削除しますか？',
    'delete_confirmation' => 'アカウントを削除するには「削除」と入力してください',
    'username_updated' => 'ユーザー名が更新されました',
    'password_updated' => 'パスワードが更新されました',
    'email_updated' => 'メールアドレスが更新されました',
    'account_deleted' => 'アカウントが削除されました',
    'current_password_incorrect' => '現在のパスワードが間違っています',
    'delete_text_incorrect' => '削除確認テキストが間違っています',
    'update' => '更新',
    'delete' => '削除',
    'current' => '現在',
    
    // フッター
    'languages' => 'Languages',
    'data_note' => '※当サイトのデータは再生リストから取得したものです。',
    'source' => 'ソース',
    'git_repository' => 'Gitリポジトリ',

    // 統計ページ
    'statistics' => '統計データ',

    // マイページ・お気に入り・動画比較
    'mypage' => 'マイページ',
    'user_info' => 'ユーザー情報',
    'registered_at' => '登録日',
    'favorites_count' => 'お気に入り: %d件',
    'view_favorites' => 'お気に入りを見る',
    'quick_links' => 'メニュー',
    'compare_help' => '動画を並べて、それぞれの開始位置を合わせてから一斉に再生します。位置は追加したあとで調整できます。',
    'compare_url_placeholder' => 'YouTubeのURL または 動画ID',
    'compare_add' => '追加',
    'compare_size' => '表示サイズ',
    'compare_size_s' => '小',
    'compare_size_m' => '中',
    'compare_size_l' => '大',
    'compare_play_all' => '同時再生',
    'compare_pause_all' => '停止',
    'compare_clear' => 'クリア',
    'compare_empty' => 'まだ動画がありません。URLを入力して「追加」、または「お気に入り」から選んでください。',
    'compare_from_favorites' => 'お気に入りから追加',
    'compare_login_required' => 'お気に入りから追加するにはログインしてください。',
    'compare_no_favorites' => '比較できるお気に入り(YouTube動画)がありません。',
    'compare_start_seconds' => '開始位置(秒)',
    'compare_current_pos' => '今の位置から始める',
    'compare_current_pos_title' => 'この比較での開始位置を、いま再生している位置にする (保存されるのはURL・マイページの比較だけ)',
    'compare_invalid_url' => 'YouTubeのURLまたは動画IDを入力してください',
    'compare_loading' => '読み込み中…',
    'close' => '閉じる',
    'no_favorites' => 'お気に入りがありません',
    'no_favorites_desc' => '動画をお気に入りに追加すると、ここに表示されます。',
    'added_date' => '追加日',
    'search_view' => '検索で見る',
    'remove' => '削除',
    'confirm_remove' => 'お気に入りから削除しますか？',
    'favorites_desc' => 'サムネイルをクリックするとその場で再生します。',
    'compare_crop' => '表示',
    'compare_crop_full' => '全体',
    'compare_crop_left' => '左半分',
    'compare_crop_right' => '右半分',
    'compare_mute' => 'ミュート',
    'compare_move_left' => '← 前へ',
    'compare_move_right' => '後ろへ →',
    'compare_join' => 'くっつけて表示',
    'compare_join_help' => '「くっつけて表示」にすると隙間なく並びます。切り取った状態では再生ボタン等が隠れるので、上の「同時再生」「停止」で操作してください。',
    'compare_relative' => '基準からの開始位置(秒)',
    'compare_relative_help' => '基準は Bad Apple!! の「流れてく 時の中ででも」の「ながれ」の頭です。各動画の基準位置は全員共通で保存されていて、ここで全体の開始位置をまとめてずらせます (マイナスなら基準より前から)。',
    'compare_base' => '基準位置(秒)',
    'compare_base_unset' => '未設定',
    'compare_base_here' => '今の位置を基準にする',
    'compare_base_save' => '保存',
    'compare_base_saved' => '保存しました',
    'compare_base_cleared' => '基準位置を削除しました',
    'compare_base_login' => '基準位置の保存にはログインが必要です',
    'compare_base_title' => '「ながれ」の頭の位置。動画が「ながれ」より後から始まる場合はマイナス。全ユーザー共通で保存されます (空にして保存すると削除)',
    'compare_copy_url' => 'URLをコピー',
    'compare_url_copied' => 'URLをコピーしました',
    'compare_save_name' => '比較の名前',
    'compare_save' => 'マイページに保存',
    'compare_saved' => 'マイページに保存しました',
    'compare_save_failed' => '保存できませんでした (名前と動画が必要です)',
    'compare_save_login' => '比較の保存にはログインが必要です',
    'saved_compares' => '保存した比較',
    'saved_compares_empty' => '保存した比較はありません。動画比較のページで「マイページに保存」すると、ここに表示されます。',
    'compare_video_count' => '%d本',
    'rename' => '名前を変更',
    'confirm_delete_compare' => 'この比較を削除しますか？',
    'compare_renamed' => '名前を変更しました',
    'compare_deleted' => '比較を削除しました',
    'compare_resume' => '再生',
    'compare_auto_sync' => 'ずれを自動で補正',
];

$_lang['en'] = [
    'year' => 'year',
    'month' => 'month',
    'week' => 'week',
    'day' => 'day',
    'hour' => 'hour',
    'minu' => 'minute',
    'sec' => 'second',
    'ago' => 'ago',
    'justnow' => 'just now',
    'title' => 'VPS Search Tool',
    'search' => 'Search',
    'and_search' => 'AND',
    'or_search' => 'OR',
    'title_checkbox' => 'Title',
    'overview_checkbox' => 'Description',
    'author_checkbox' => 'Author',
    'tag_checkbox' => 'Tag',
    'unlisted_checkbox' => 'Unlisted',
    'deleted_checkbox' => 'Deleted',
    'all_radio' => 'All',
    'vps_radio' => 'VPS',
    'material_radio' => 'Material',
    'use_ai_class' => 'AI Classification',
    'next' => 'Next',
    'prev' => 'Prev',
    'sended_pl' => 'Sended playlist',
    'added_pl' => 'Added playlist',
    'sended_vd' => 'Sended video',
    'added_vd' => 'Added video',
    'reported_video' => 'Reported video',
    'send_pl' => 'Data Sending',
    'info' => 'Info',
    'compare' => 'Compare',
    'view' => 'views',
    'report' => 'Report',
    'download' => 'Download',
    'copy' => 'Copy',

    'sort' => 'Sort',
    'sort_recent' => 'Recent',
    'sort_ancient' => 'Ancient',
    'sort_most_view' => 'Most View',
    'sort_worst_view' => 'Worst View',
    'sort_most_like' => 'Most Like',
    'sort_word' => 'Word Asc',
    'sort_word_desc' => 'Word Desc',
    'sort_random' => 'Random',

    'total' => 'Total',
    'next_birth' => 'Next %dth anniversary %d days',

    'listview' => 'List View',
    'matrixview' => 'Matrix View',

    'lightmode' => 'Light Mode',
    'darkmode' => 'Dark Mode',

    // 認証関連
    'login' => 'Login',
    'logout' => 'Logout',
    'register' => 'Register',
    'username' => 'Username',
    'password' => 'Password',
    'email' => 'Email',
    'login_required' => 'Login required',

    // お気に入り関連
    'favorites' => 'Favorites',
    'add_to_favorites' => 'Add to favorites',
    'remove_from_favorites' => 'Remove from favorites',
    'added_to_favorites' => 'Added to favorites',
    'removed_from_favorites' => 'Removed from favorites',
    'error_occurred' => 'An error occurred',
    
    // 認証エラーメッセージ
    'username_already_exists' => 'Username already exists',
    'email_already_exists' => 'Email already exists',
    'account_created' => 'Account created successfully',
    'login_success' => 'Login successful',
    'invalid_credentials' => 'Invalid username or password',
    'logout_success' => 'Logout successful',
    'username_password_required' => 'Please enter username and password',
    
    // 登録フォーム関連
    'register_title' => 'Register',
    'register_button' => 'Register',
    'confirm_password' => 'Confirm Password',
    'redirect_to_login' => 'Please go to the login page.',
    'valid_email_required' => 'Please enter a valid email address',
    'password_min_length' => 'Password must be at least 6 characters',
    'password_mismatch' => 'Passwords do not match',
    'all_fields_required' => 'Please fill in all fields',
    'already_have_account' => 'Already have an account?',
    
    // アカウント設定関連
    'account_settings' => 'Account Settings',
    'change_username' => 'Change Username',
    'change_password' => 'Change Password',
    'change_email' => 'Change Email',
    'delete_account' => 'Delete Account',
    'new_username' => 'New Username',
    'current_password' => 'Current Password',
    'new_password' => 'New Password',
    'new_email' => 'New Email',
    'confirm_delete' => 'Are you sure you want to delete your account?',
    'delete_confirmation' => 'Type "DELETE" to confirm account deletion',
    'username_updated' => 'Username updated successfully',
    'password_updated' => 'Password updated successfully',
    'email_updated' => 'Email updated successfully',
    'account_deleted' => 'Account deleted successfully',
    'current_password_incorrect' => 'Current password is incorrect',
    'delete_text_incorrect' => 'Delete confirmation text is incorrect',
    'update' => 'Update',
    'delete' => 'Delete',
    'current' => 'Current',
    
    // Footer
    'languages' => 'Languages',
    'data_note' => '※The data on this site is obtained from playlists.',
    'source' => 'Source',
    'git_repository' => 'Git Repository',

    // 統計ページ
    'statistics' => 'Statistics',

    // マイページ・お気に入り・動画比較
    'mypage' => 'My Page',
    'user_info' => 'User Info',
    'registered_at' => 'Registered',
    'favorites_count' => 'Favorites: %d',
    'view_favorites' => 'View favorites',
    'quick_links' => 'Menu',
    'compare_help' => 'Line up videos, align each start position, then play them all at once. Positions can be adjusted after adding.',
    'compare_url_placeholder' => 'YouTube URL or video ID',
    'compare_add' => 'Add',
    'compare_size' => 'Size',
    'compare_size_s' => 'S',
    'compare_size_m' => 'M',
    'compare_size_l' => 'L',
    'compare_play_all' => 'Play all',
    'compare_pause_all' => 'Pause',
    'compare_clear' => 'Clear',
    'compare_empty' => 'No videos yet. Enter a URL and press "Add", or pick from "Favorites".',
    'compare_from_favorites' => 'Add from favorites',
    'compare_login_required' => 'Please log in to add from favorites.',
    'compare_no_favorites' => 'No favorites (YouTube videos) available to compare.',
    'compare_start_seconds' => 'Start (sec)',
    'compare_current_pos' => 'Start from here',
    'compare_current_pos_title' => 'Use the current position as the start position',
    'compare_invalid_url' => 'Please enter a YouTube URL or video ID',
    'compare_loading' => 'Loading…',
    'close' => 'Close',
    'no_favorites' => 'No favorites',
    'no_favorites_desc' => 'Videos you add to favorites will appear here.',
    'added_date' => 'Added',
    'search_view' => 'View in search',
    'remove' => 'Remove',
    'confirm_remove' => 'Remove from favorites?',
    'favorites_desc' => 'Click a thumbnail to play it in place.',
    'compare_crop' => 'View',
    'compare_crop_full' => 'Full',
    'compare_crop_left' => 'Left half',
    'compare_crop_right' => 'Right half',
    'compare_mute' => 'Mute',
    'compare_move_left' => '← Earlier',
    'compare_move_right' => 'Later →',
    'compare_join' => 'Join side by side',
    'compare_join_help' => '"Join side by side" removes the gaps. Cropped players hide their own controls, so use "Play all" and "Pause" above.',
    'compare_relative' => 'Start relative to reference (sec)',
    'compare_relative_help' => 'The reference is the start of "nagare" in Bad Apple!! ("Nagareteku toki no naka de demo"). Each video\'s reference position is shared by everyone, and this shifts the start of all videos at once (negative = before the reference).',
    'compare_base' => 'Reference (sec)',
    'compare_base_unset' => 'Not set',
    'compare_base_here' => 'Set current position as reference',
    'compare_base_save' => 'Save',
    'compare_base_saved' => 'Saved',
    'compare_base_cleared' => 'Reference position removed',
    'compare_base_login' => 'Log in to save reference positions',
    'compare_base_title' => 'Where "nagare" starts; negative if the video begins after it. Shared by all users (save an empty value to remove)',
    'compare_copy_url' => 'Copy URL',
    'compare_url_copied' => 'URL copied',
    'compare_save_name' => 'Comparison name',
    'compare_save' => 'Save to My Page',
    'compare_saved' => 'Saved to My Page',
    'compare_save_failed' => 'Could not save (a name and at least one video are required)',
    'compare_save_login' => 'Log in to save comparisons',
    'saved_compares' => 'Saved comparisons',
    'saved_compares_empty' => 'No saved comparisons. Use "Save to My Page" on the Compare page to add one.',
    'compare_video_count' => '%d videos',
    'rename' => 'Rename',
    'confirm_delete_compare' => 'Delete this comparison?',
    'compare_renamed' => 'Renamed',
    'compare_deleted' => 'Comparison deleted',
    'compare_resume' => 'Resume',
    'compare_auto_sync' => 'Auto-correct drift',
];

$_lang['zh'] = [
    'year' => '年',
    'month' => '个月',
    'week' => '周',
    'day' => '天',
    'hour' => '小时',
    'minu' => '分钟',
    'sec' => '秒',
    'ago' => '前',
    'justnow' => '刚刚',
    'title' => '口技対決搜索工具',
    'search' => '搜索',
    'and_search' => 'AND搜索',
    'or_search' => 'OR搜索',
    'title_checkbox' => '标题',
    'overview_checkbox' => '概述',
    'author_checkbox' => '投稿者',
    'tag_checkbox' => '标签',
    'unlisted_checkbox' => '限量发售',
    'deleted_checkbox' => '已删除',
    'all_radio' => '全部',
    'vps_radio' => '语音对决',
    'material_radio' => '素材',
    'use_ai_class' => 'AI分类',
    'next' => '下一页',
    'prev' => '上一页',
    'sended_pl' => '已发送播放列表。',
    'added_pl' => '已添加到播放列表。',
    'sended_vd' => '已发送播视频。',
    'added_vd' => '已添加到播视频。',
    'reported_video' => '已举报视频。',
    'send_pl' => '数据传输',
    'info' => '信息',
    'compare' => '视频对比',
    'view' => '次观看',
    'report' => '举报',
    'download' => '下载',
    'copy' => '复制',

    'sort' => '排序',
    'sort_recent' => '按最新发布日期排序',
    'sort_ancient' => '按最旧发布日期排序',
    'sort_most_view' => '按观看次数最多排序',
    'sort_worst_view' => '按观看次数最少排序',
    'sort_most_like' => '按点赞次数最多排序',
    'sort_word' => '按标题升序排序',
    'sort_word_desc' => '按标题降序排序',
    'sort_random' => '随机排序',

    'total' => '总计',
    'next_birth' => '距离%d周年还有%d天',

    'listview' => '列表视图',
    'matrixview' => '矩阵视图',

    'lightmode' => '明亮模式',
    'darkmode' => '黑暗模式',

    // 认证相关
    'login' => '登录',
    'logout' => '登出',
    'register' => '注册',
    'username' => '用户名',
    'password' => '密码',
    'email' => '邮箱',
    'login_required' => '需要登录',

    // 收藏相关
    'favorites' => '收藏',
    'add_to_favorites' => '添加到收藏',
    'remove_from_favorites' => '从收藏中删除',
    'added_to_favorites' => '已添加到收藏',
    'removed_from_favorites' => '已从收藏中删除',
    'error_occurred' => '发生错误',

    // 认证错误信息
    'username_already_exists' => '用户名已存在',
    'email_already_exists' => '邮箱已存在',
    'account_created' => '账户创建成功',
    'login_success' => '登录成功',
    'invalid_credentials' => '用户名或密码错误',
    'logout_success' => '退出登录成功',
    'username_password_required' => '请输入用户名和密码',

    // 注册表单相关
    'register_title' => '注册',
    'register_button' => '注册',
    'confirm_password' => '确认密码',
    'redirect_to_login' => '请前往登录页面。',
    'valid_email_required' => '请输入有效的邮箱地址',
    'password_min_length' => '密码至少需要6个字符',
    'password_mismatch' => '密码不匹配',
    'all_fields_required' => '请填写所有字段',
    'already_have_account' => '已有账户？',

    // 账户设置相关
    'account_settings' => '账户设置',
    'change_username' => '更改用户名',
    'change_password' => '更改密码',
    'change_email' => '更改邮箱',
    'delete_account' => '删除账户',
    'new_username' => '新用户名',
    'current_password' => '当前密码',
    'new_password' => '新密码',
    'new_email' => '新邮箱',
    'confirm_delete' => '确定要删除账户吗？',
    'delete_confirmation' => '输入"删除"确认删除账户',
    'username_updated' => '用户名更新成功',
    'password_updated' => '密码更新成功',
    'email_updated' => '邮箱更新成功',
    'account_deleted' => '账户删除成功',
    'current_password_incorrect' => '当前密码错误',
    'delete_text_incorrect' => '删除确认文本错误',
    'update' => '更新',
    'delete' => '删除',
    'current' => '当前',
    
    // 页脚
    'languages' => 'Languages',
    'data_note' => '※本站数据来自播放列表。',
    'source' => '来源',
    'git_repository' => 'Git 仓库',

    // 统计
    'statistics' => '统计',

    // マイページ・お気に入り・動画比較
    'mypage' => '我的页面',
    'user_info' => '用户信息',
    'registered_at' => '注册日期',
    'favorites_count' => '收藏: %d 个',
    'view_favorites' => '查看收藏',
    'quick_links' => '菜单',
    'compare_help' => '将视频并排，对齐各自的开始位置后同时播放。添加后可调整位置。',
    'compare_url_placeholder' => 'YouTube 网址或视频 ID',
    'compare_add' => '添加',
    'compare_size' => '显示大小',
    'compare_size_s' => '小',
    'compare_size_m' => '中',
    'compare_size_l' => '大',
    'compare_play_all' => '同时播放',
    'compare_pause_all' => '暂停',
    'compare_clear' => '清除',
    'compare_empty' => '还没有视频。输入网址并点击“添加”，或从“收藏”中选择。',
    'compare_from_favorites' => '从收藏中添加',
    'compare_login_required' => '请登录后从收藏中添加。',
    'compare_no_favorites' => '没有可对比的收藏（YouTube 视频）。',
    'compare_start_seconds' => '开始位置(秒)',
    'compare_current_pos' => '从当前位置开始',
    'compare_current_pos_title' => '将当前位置设为开始位置',
    'compare_invalid_url' => '请输入 YouTube 网址或视频 ID',
    'compare_loading' => '加载中…',
    'close' => '关闭',
    'no_favorites' => '没有收藏',
    'no_favorites_desc' => '添加到收藏的视频会显示在这里。',
    'added_date' => '添加日期',
    'search_view' => '在搜索中查看',
    'remove' => '删除',
    'confirm_remove' => '要从收藏中删除吗？',
    'favorites_desc' => '点击缩略图即可在此播放。',
    'compare_crop' => '显示',
    'compare_crop_full' => '全部',
    'compare_crop_left' => '左半边',
    'compare_crop_right' => '右半边',
    'compare_mute' => '静音',
    'compare_move_left' => '← 前移',
    'compare_move_right' => '后移 →',
    'compare_join' => '无缝拼接显示',
    'compare_join_help' => '开启“无缝拼接显示”后视频之间没有间隙。裁剪后播放器自身的按钮会被遮住，请使用上方的“同时播放”“暂停”。',
    'compare_relative' => '相对基准的开始位置(秒)',
    'compare_relative_help' => '基准是 Bad Apple!!「流れてく 時の中ででも」中「ながれ」的开头。各视频的基准位置由所有人共享，可在此统一调整所有视频的开始位置（负数表示从基准之前开始）。',
    'compare_base' => '基准位置(秒)',
    'compare_base_unset' => '未设置',
    'compare_base_here' => '把当前位置设为基准',
    'compare_base_save' => '保存',
    'compare_base_saved' => '已保存',
    'compare_base_cleared' => '已删除基准位置',
    'compare_base_login' => '保存基准位置需要登录',
    'compare_base_title' => '「ながれ」开头的位置，视频在其之后才开始时为负数。所有用户共享（保存空值即删除）',
    'compare_copy_url' => '复制网址',
    'compare_url_copied' => '已复制网址',
    'compare_save_name' => '对比名称',
    'compare_save' => '保存到我的页面',
    'compare_saved' => '已保存到我的页面',
    'compare_save_failed' => '无法保存（需要名称和至少一个视频）',
    'compare_save_login' => '保存对比需要登录',
    'saved_compares' => '已保存的对比',
    'saved_compares_empty' => '没有已保存的对比。在视频对比页面点击“保存到我的页面”后会显示在这里。',
    'compare_video_count' => '%d 个视频',
    'rename' => '重命名',
    'confirm_delete_compare' => '要删除这个对比吗？',
    'compare_renamed' => '已重命名',
    'compare_deleted' => '已删除对比',
    'compare_resume' => '继续播放',
    'compare_auto_sync' => '自动校正偏差',
];

$_lang['ko'] = [
    'year' => '년',
    'month' => '개월',
    'week' => '주',
    'day' => '일',
    'hour' => '시간',
    'minu' => '분',
    'sec' => '초',
    'ago' => '전',
    'justnow' => '방금',
    'title' => '보이파대결 전용 검색 도구',
    'search' => '검색',
    'and_search' => 'AND 검색',
    'or_search' => 'OR 검색',
    'title_checkbox' => '제목',
    'overview_checkbox' => '개요',
    'author_checkbox' => '게시자',
    'tag_checkbox' => '태그',
    'unlisted_checkbox' => '한정 공개',
    'deleted_checkbox' => '삭제됨',
    'all_radio' => '모두',
    'vps_radio' => '보이스피싱 대결',
    'material_radio' => '소재',
    'use_ai_class' => 'AI 분류',
    'next' => '다음',
    'prev' => '이전',
    'sended_pl' => '재생 목록을 전송했습니다.',
    'added_pl' => '재생 목록에 추가했습니다.',
    'sended_vd' => '동영상 전송했습니다.',
    'added_vd' => '동영상 추가했습니다.',
    'reported_video' => '동영상을 신고했습니다.',
    'send_pl' => '데이터 전송',
    'info' => '정보',
    'compare' => '동영상 비교',
    'view' => '회 시청',
    'report' => '신고',
    'download' => '다운로드',
    'copy' => '복사',

    'sort' => '정렬',
    'sort_recent' => '최신 게시 날짜순',
    'sort_ancient' => '오래된 게시 날짜순',
    'sort_most_view' => '시청 횟수가 많은 순',
    'sort_worst_view' => '시청 횟수가 적은 순',
    'sort_most_like' => '좋아요가 많은 순',
    'sort_word' => '제목 오름차순',
    'sort_word_desc' => '제목 내림차순',
    'sort_random' => '무작위 정렬',

    'total' => '총계',
    'next_birth' => '보이스피싱 대결 %d주년까지 %d일 남음',

    'listview' => '목록 표시 모드',
    'matrixview' => '행렬 표시 모드',

    'lightmode' => '라이트 모드',
    'darkmode' => '다크 모드',

    // 인증 관련
    'login' => '로그인',
    'logout' => '로그아웃',
    'register' => '회원가입',
    'username' => '사용자명',
    'password' => '비밀번호',
    'email' => '이메일',
    'login_required' => '로그인이 필요합니다',

    // 즐겨찾기 관련
    'favorites' => '즐겨찾기',
    'add_to_favorites' => '즐겨찾기에 추가',
    'remove_from_favorites' => '즐겨찾기에서 삭제',
    'added_to_favorites' => '즐겨찾기에 추가되었습니다',
    'removed_from_favorites' => '즐겨찾기에서 삭제되었습니다',
    'error_occurred' => '오류가 발생했습니다',

    // 인증 오류 메시지
    'username_already_exists' => '사용자명이 이미 존재합니다',
    'email_already_exists' => '이메일이 이미 존재합니다',
    'account_created' => '계정이 생성되었습니다',
    'login_success' => '로그인되었습니다',
    'invalid_credentials' => '사용자명 또는 비밀번호가 잘못되었습니다',
    'logout_success' => '로그아웃되었습니다',
    'username_password_required' => '사용자명과 비밀번호를 입력하세요',

    // 등록 양식 관련
    'register_title' => '회원가입',
    'register_button' => '등록',
    'confirm_password' => '비밀번호 확인',
    'redirect_to_login' => '로그인 페이지로 이동해주세요.',
    'valid_email_required' => '유효한 이메일 주소를 입력해주세요',
    'password_min_length' => '비밀번호는 최소 6자 이상이어야 합니다',
    'password_mismatch' => '비밀번호가 일치하지 않습니다',
    'all_fields_required' => '모든 항목을 입력해주세요',
    'already_have_account' => '이미 계정이 있으신가요?',

    // 계정 설정 관련
    'account_settings' => '계정 설정',
    'change_username' => '사용자명 변경',
    'change_password' => '비밀번호 변경',
    'change_email' => '이메일 변경',
    'delete_account' => '계정 삭제',
    'new_username' => '새 사용자명',
    'current_password' => '현재 비밀번호',
    'new_password' => '새 비밀번호',
    'new_email' => '새 이메일',
    'confirm_delete' => '정말로 계정을 삭제하시겠습니까？',
    'delete_confirmation' => '계정 삭제를 확인하려면 "삭제"를 입력하세요',
    'username_updated' => '사용자명이 업데이트되었습니다',
    'password_updated' => '비밀번호가 업데이트되었습니다',
    'email_updated' => '이메일이 업데이트되었습니다',
    'account_deleted' => '계정이 삭제되었습니다',
    'current_password_incorrect' => '현재 비밀번호가 틀렸습니다',
    'delete_text_incorrect' => '삭제 확인 텍스트가 틀렸습니다',
    'update' => '업데이트',
    'delete' => '삭제',
    'current' => '현재',

    // 푸터
    'languages' => 'Languages',
    'data_note' => '※이 사이트의 데이터는 재생목록에서 가져왔습니다.',
    'source' => '소스',
    'git_repository' => 'Git 저장소',

    // 통계
    'statistics' => '통계',

    // マイページ・お気に入り・動画比較
    'mypage' => '마이페이지',
    'user_info' => '사용자 정보',
    'registered_at' => '가입일',
    'favorites_count' => '즐겨찾기: %d개',
    'view_favorites' => '즐겨찾기 보기',
    'quick_links' => '메뉴',
    'compare_help' => '동영상을 나란히 놓고 각각의 시작 위치를 맞춘 뒤 한꺼번에 재생합니다. 위치는 추가한 후에 조정할 수 있습니다.',
    'compare_url_placeholder' => 'YouTube URL 또는 동영상 ID',
    'compare_add' => '추가',
    'compare_size' => '표시 크기',
    'compare_size_s' => '소',
    'compare_size_m' => '중',
    'compare_size_l' => '대',
    'compare_play_all' => '동시 재생',
    'compare_pause_all' => '정지',
    'compare_clear' => '지우기',
    'compare_empty' => '아직 동영상이 없습니다. URL을 입력하고 "추가"를 누르거나 "즐겨찾기"에서 선택하세요.',
    'compare_from_favorites' => '즐겨찾기에서 추가',
    'compare_login_required' => '즐겨찾기에서 추가하려면 로그인하세요.',
    'compare_no_favorites' => '비교할 수 있는 즐겨찾기(YouTube 동영상)가 없습니다.',
    'compare_start_seconds' => '시작 위치(초)',
    'compare_current_pos' => '현재 위치에서 시작',
    'compare_current_pos_title' => '지금 표시된 위치를 시작 위치로 설정',
    'compare_invalid_url' => 'YouTube URL 또는 동영상 ID를 입력하세요',
    'compare_loading' => '불러오는 중…',
    'close' => '닫기',
    'no_favorites' => '즐겨찾기가 없습니다',
    'no_favorites_desc' => '즐겨찾기에 추가한 동영상이 여기에 표시됩니다.',
    'added_date' => '추가일',
    'search_view' => '검색에서 보기',
    'remove' => '삭제',
    'confirm_remove' => '즐겨찾기에서 삭제하시겠습니까?',
    'favorites_desc' => '썸네일을 클릭하면 그 자리에서 재생됩니다.',
    'compare_crop' => '표시',
    'compare_crop_full' => '전체',
    'compare_crop_left' => '왼쪽 절반',
    'compare_crop_right' => '오른쪽 절반',
    'compare_mute' => '음소거',
    'compare_move_left' => '← 앞으로',
    'compare_move_right' => '뒤로 →',
    'compare_join' => '붙여서 표시',
    'compare_join_help' => '"붙여서 표시"를 켜면 틈 없이 나란히 표시됩니다. 잘라낸 상태에서는 재생 버튼 등이 가려지므로 위의 "동시 재생", "정지"로 조작하세요.',
    'compare_relative' => '기준에서의 시작 위치(초)',
    'compare_relative_help' => '기준은 Bad Apple!!의 「流れてく 時の中ででも」 중 「ながれ」의 시작입니다. 각 동영상의 기준 위치는 모두가 공유하며, 여기서 전체 시작 위치를 한꺼번에 옮길 수 있습니다 (음수면 기준보다 앞에서 시작).',
    'compare_base' => '기준 위치(초)',
    'compare_base_unset' => '미설정',
    'compare_base_here' => '현재 위치를 기준으로 설정',
    'compare_base_save' => '저장',
    'compare_base_saved' => '저장했습니다',
    'compare_base_cleared' => '기준 위치를 삭제했습니다',
    'compare_base_login' => '기준 위치를 저장하려면 로그인하세요',
    'compare_base_title' => '「ながれ」가 시작되는 위치. 동영상이 그보다 늦게 시작하면 음수. 모든 사용자가 공유합니다 (빈 값으로 저장하면 삭제)',
    'compare_copy_url' => 'URL 복사',
    'compare_url_copied' => 'URL을 복사했습니다',
    'compare_save_name' => '비교 이름',
    'compare_save' => '마이페이지에 저장',
    'compare_saved' => '마이페이지에 저장했습니다',
    'compare_save_failed' => '저장할 수 없습니다 (이름과 동영상이 필요합니다)',
    'compare_save_login' => '비교를 저장하려면 로그인하세요',
    'saved_compares' => '저장한 비교',
    'saved_compares_empty' => '저장한 비교가 없습니다. 동영상 비교 페이지에서 "마이페이지에 저장"을 누르면 여기에 표시됩니다.',
    'compare_video_count' => '%d개',
    'rename' => '이름 변경',
    'confirm_delete_compare' => '이 비교를 삭제하시겠습니까?',
    'compare_renamed' => '이름을 변경했습니다',
    'compare_deleted' => '비교를 삭제했습니다',
    'compare_resume' => '재생',
    'compare_auto_sync' => '어긋남 자동 보정',
];
