<?php
global $_lang;

$_lang['ja'] = [
    'year' => '年',
    'month' => 'ヶ月',
    'week' => '週',
    'day' => '日',
    'hour' => '時',
    'minu' => '分',
    'sec' => '秒',
    'ago' => '前',
    'justnow' => '直前',
    'title' => 'ボ対検索ツール',
    'search' => '検索',
    'and_search' => 'AND検索',
    'or_search' => 'OR検索',
    'title_checkbox' => 'タイトル',
    'overview_checkbox' => '概要欄',
    'author_checkbox' => '投稿者',
    'tag_checkbox' => 'タグ',
    'unlisted_checkbox' => '限定公開',
    'deleted_checkbox' => '削除済み',
    'all_radio' => 'すべて',
    'vps_radio' => 'ボイパ対決',
    'material_radio' => '素材',
    'use_ai_class' => 'AIによる分類',
    'next' => '次へ',
    'prev' => '前へ',
    'sended_pl' => 'プレイリストを送信しました。',
    'added_pl' => 'プレイリストを追加しました。',
    'sended_vd' => '動画を送信しました。',
    'added_vd' => '動画を追加しました。',
    'reported_video' => '動画を報告しました。',
    'send_pl' => 'データ送信',
    'info' => '情報',
    'view' => '回視聴',
    'report' => '報告',
    'download' => 'ダウンロード',
    'copy' => 'コピー',

    'sort' => '並び替え',
    'sort_recent' => '投稿日時が新しい順',
    'sort_ancient' => '投稿日時が古い順',
    'sort_most_view' => '再生数が多い順',
    'sort_worst_view' => '再生数が少ない順',
    'sort_most_like' => '高評価が多い順',
    'sort_word' => 'タイトル昇順',
    'sort_word_desc' => 'タイトル降順',

    'total' => '合計',
    'next_birth' => 'ボイパ対決%d周年まであと%d日',

    'listview' => '一覧表示モード',
    'matrixview' => '行列表示モード',

    'lightmode' => 'ライトモード',
    'darkmode' => 'ダークモード',
];

$_lang['en'] = [
    'year' => 'year',
    'month' => 'month',
    'week' => 'week',
    'day' => 'day',
    'hour' => 'hour',
    'minu' => 'minute',
    'sec' => 'second',
    'ago' => 'ago',
    'justnow' => 'just now',
    'title' => 'VPS Search Tool',
    'search' => 'Search',
    'and_search' => 'AND',
    'or_search' => 'OR',
    'title_checkbox' => 'Title',
    'overview_checkbox' => 'Description',
    'author_checkbox' => 'Author',
    'tag_checkbox' => 'Tag',
    'unlisted_checkbox' => 'Unlisted',
    'deleted_checkbox' => 'Deleted',
    'all_radio' => 'All',
    'vps_radio' => 'VPS',
    'material_radio' => 'Material',
    'use_ai_class' => 'AI Classification',
    'next' => 'Next',
    'prev' => 'Prev',
    'sended_pl' => 'Sended playlist',
    'added_pl' => 'Added playlist',
    'sended_vd' => 'Sended video',
    'added_vd' => 'Added video',
    'reported_video' => 'Reported video',
    'send_pl' => 'Data Sending',
    'info' => 'Info',
    'view' => 'views',
    'report' => 'Report',
    'download' => 'Download',
    'copy' => 'Copy',

    'sort' => 'Sort',
    'sort_recent' => 'Recent',
    'sort_ancient' => 'Ancient',
    'sort_most_view' => 'Most View',
    'sort_worst_view' => 'Worst View',
    'sort_most_like' => 'Most Like',
    'sort_word' => 'Word Asc',
    'sort_word_desc' => 'Word Desc',

    'total' => 'Total',
    'next_birth' => 'Next %dth anniversary %d days',

    'listview' => 'List View',
    'matrixview' => 'Matrix View',

    'lightmode' => 'Light Mode',
    'darkmode' => 'Dark Mode',
];

$_lang['zh'] = [
'year' => '年',
'month' => '个月',
'week' => '周',
'day' => '天',
'hour' => '小时',
'minu' => '分钟',
'sec' => '秒',
'ago' => '前',
'justnow' => '刚刚',
'title' => '口技対決搜索工具',
'search' => '搜索',
'and_search' => 'AND搜索',
'or_search' => 'OR搜索',
'title_checkbox' => '标题',
'overview_checkbox' => '概述',
'author_checkbox' => '投稿者',
'tag_checkbox' => '标签',
'unlisted_checkbox' => '限量发售',
'deleted_checkbox' => '已删除',
'all_radio' => '全部',
'vps_radio' => '语音对决',
'material_radio' => '素材',
'use_ai_class' => 'AI分类',
'next' => '下一页',
'prev' => '上一页',
'sended_pl' => '已发送播放列表。',
'added_pl' => '已添加到播放列表。',
'sended_vd' => '已发送播视频。',
'added_vd' => '已添加到播视频。',
'reported_video' => '已举报视频。',
'send_pl' => '数据传输',
'info' => '信息',
'view' => '次观看',
'report' => '举报',
'download' => '下载',
'copy' => '复制',

'sort' => '排序',
'sort_recent' => '按最新发布日期排序',
'sort_ancient' => '按最旧发布日期排序',
'sort_most_view' => '按观看次数最多排序',
'sort_worst_view' => '按观看次数最少排序',
'sort_most_like' => '按点赞次数最多排序',
'sort_word' => '按标题升序排序',
'sort_word_desc' => '按标题降序排序',

'total' => '总计',
'next_birth' => '距离%d周年还有%d天',

'listview' => '列表视图',
'matrixview' => '矩阵视图',

'lightmode' => '明亮模式',
'darkmode' => '黑暗模式',
];

$_lang['ko'] = [
'year' => '년',
'month' => '개월',
'week' => '주',
'day' => '일',
'hour' => '시간',
'minu' => '분',
'sec' => '초',
'ago' => '전',
'justnow' => '방금',
'title' => '보이파대결 전용 검색 도구',
'search' => '검색',
'and_search' => 'AND 검색',
'or_search' => 'OR 검색',
'title_checkbox' => '제목',
'overview_checkbox' => '개요',
'author_checkbox' => '게시자',
'tag_checkbox' => '태그',
'unlisted_checkbox' => '한정 공개',
'deleted_checkbox' => '삭제됨',
'all_radio' => '모두',
'vps_radio' => '보이스피싱 대결',
'material_radio' => '소재',
'use_ai_class' => 'AI 분류',
'next' => '다음',
'prev' => '이전',
'sended_pl' => '재생 목록을 전송했습니다.',
'added_pl' => '재생 목록에 추가했습니다.',
'sended_vd' => '동영상 전송했습니다.',
'added_vd' => '동영상 추가했습니다.',
'reported_video' => '동영상을 신고했습니다.',
'send_pl' => '데이터 전송',
'info' => '정보',
'view' => '회 시청',
'report' => '신고',
'download' => '다운로드',
'copy' => '복사',

'sort' => '정렬',
'sort_recent' => '최신 게시 날짜순',
'sort_ancient' => '오래된 게시 날짜순',
'sort_most_view' => '시청 횟수가 많은 순',
'sort_worst_view' => '시청 횟수가 적은 순',
'sort_most_like' => '좋아요가 많은 순',
'sort_word' => '제목 오름차순',
'sort_word_desc' => '제목 내림차순',

'total' => '총계',
'next_birth' => '보이스피싱 대결 %d주년까지 %d일 남음',

'listview' => '목록 표시 모드',
'matrixview' => '행렬 표시 모드',

'lightmode' => '라이트 모드',
'darkmode' => '다크 모드',
];
