<?php
// admin/lang.php
// 管理画面の文言。使うのは管理者1人なので日本語だけ用意する

$_adminLang['ja'] = [
    'title' => '管理画面',
    'back_to_site' => 'サイトに戻る',
    'forbidden' => 'このページは管理者のみ利用できます。',
    'forbidden_hint' => '管理者の ChreeID でログインしてください。',
    'login_chreeid' => 'ChreeIDでログイン',
    'failed' => '操作に失敗しました',
    'csrf_failed' => 'ページの有効期限が切れました。もう一度操作してください。',

    'tab_reports' => '通報',
    'tab_blacklist' => 'ブラックリスト',
    'tab_data' => 'データ',
    'tab_users' => 'ユーザー',
    'tab_stats' => '統計',

    'reports_empty' => '通報はありません。',
    'report_date' => '日時',
    'report_video' => '動画',
    'report_type' => '内容',
    'report_reason' => '理由',
    'report_done' => '対応済みにしました',
    'report_done_button' => '対応済み',
    'report_blacklist_button' => 'ブラックリストに追加',

    'blacklist_help' => 'ここに入れた動画IDは検索結果に出なくなります。外した動画は次回のデータ更新で戻ります。',
    'blacklist_empty' => 'ブラックリストは空です。',
    'blacklist_id' => '動画ID',
    'blacklist_add_button' => '追加',
    'blacklist_remove_button' => '外す',
    'blacklist_added' => 'ブラックリストに追加しました',
    'blacklist_removed' => 'ブラックリストから外しました',

    'data_update_heading' => 'データ更新',
    'data_last_update' => '最終更新',
    'data_update_button' => '今すぐ更新',
    'data_full_update_button' => '全件取り直す',
    'data_update_help' => '「全件取り直す」は再生リストを最後まで辿るので時間がかかります。',
    'data_updated' => 'データを更新しました',
    'data_add_heading' => '再生リスト・動画の登録',
    'data_add_placeholder' => '再生リスト / YouTube / ニコニコ動画 のURL',
    'data_add_button' => '登録',
    'data_added' => '登録しました',
    'queue_heading' => '投稿キュー',
    'queue_empty' => '投稿はありません。',
    'queue_url' => 'URL',
    'queue_type' => '種類',
    'queue_approve_button' => '登録する',
    'queue_reject_button' => '却下',
    'queue_rejected' => '却下しました',
    'stats_videos_heading' => '収録動画',
    'stats_videos_total' => '合計',
    'stats_latest_video' => '最新の動画',
    'stats_search_heading' => '検索',
    'stats_days' => '直近%d日',
    'stats_total' => '検索 %d 回',
    'stats_top_words' => 'よく検索されたワード',
    'stats_recent_words' => '最近の検索',
    'stats_daily' => '日別の検索回数',
    'stats_word' => 'ワード',
    'stats_count' => '回数',
    'stats_date' => '日付',
    'stats_empty' => 'まだ検索はありません。',

    'users_count' => '%d 人',
    'user_name' => 'ユーザー名',
    'user_email' => 'メールアドレス',
    'user_created' => '登録日',
    'user_chreeid' => 'ChreeID',
    'user_favorites' => 'お気に入り',
    'user_delete_button' => '削除',
    'user_delete_confirm' => 'このユーザーとお気に入りを削除しますか？',
    'user_deleted' => 'ユーザーを削除しました',
    'user_self' => '(自分)',
    'confirm' => '実行しますか？',
];
